# Generated by Django 6.0.5 on 2026-05-15 08:14

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'png', 'jpg', 'jpeg']), core.models.validate_file_size]),
        ),
    ]
