# Generated by Django 6.0.5 on 2026-06-02 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_uploadedfile_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Filament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=160)),
                ("material", models.CharField(max_length=80)),
                (
                    "color_mode",
                    models.CharField(
                        choices=[
                            ("single", "Single color"),
                            ("dual", "Dual color"),
                            ("tricolor", "Tri-color"),
                            ("gradient", "Gradient"),
                            ("custom", "Custom / other"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(max_length=80)),
                ("secondary_color", models.CharField(blank=True, max_length=80)),
                ("tertiary_color", models.CharField(blank=True, max_length=80)),
                ("gradient_description", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_filaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["manufacturer__name", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Spool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spool_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "remaining_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("in_use", "In use"),
                            ("low", "Low stock"),
                            ("empty", "Empty"),
                            ("ordered", "Ordered"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_spools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
        migrations.AddField(
            model_name="filament",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="filaments",
                to="core.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="spool",
            name="filament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spools",
                to="core.filament",
            ),
        ),
    ]
