# Generated by Django 6.0.5 on 2026-06-05 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_filament_manufacturer_spool_delete_uploadedfile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spool",
            name="price_per_spool",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
